import Head from "next/head";
import Todo from "../components/Todo";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { AiOutlineAlignLeft } from "react-icons/ai";

export default function Home() {
  const [input, setInput] = useState(null);
  const [data, setData] = useState([]);

  const  getData = async()=> {
    await fetch("/api/tasks", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
      
    }).then(response => response.json())
    .then(data => setData(data));

  }

 
  
  const deleteTodoById = async (id) => {

    await fetch(`/api/tasks/${id}`, {
      method: "DELETE",
      headers: {
        "Content-Type": "application/json",
      },
    }).then(response => response.json())
   

  };
  useEffect(() => {
    getData()
  }, [deleteTodoById])

  const handleChange = (e) => {
    setInput(e.target.value);
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter") {
      handleTodo(input);
      e.target.value = null;
    }
  };

  const handleTodo = async (input) => {
    await fetch("/api/tasks", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ title: input }),
    }).then(response => response.json())
    .then(data => setData((prevState)=> [...prevState, data]));

  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Todos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.todoapp}>
        <div className={styles.todo}>
          <div className={styles.header}>
            <span className={styles.title}>To Do List</span>
          </div>
          <div className={styles.form}>
            <div className={styles.addTodo}>
              <div className={styles.addTask}>
                <p>
                  <AiOutlineAlignLeft />
                </p>

                <input
                  placeholder="Add a task..."
                  name="title"
                  onChange={handleChange}
                  onKeyDown={handleKeyDown}
                  className={styles.todoInput}
                />
              </div>
              <div className={styles.pintle}>
                {data?.map(
                  (item) =>
                    item?.pintle && (
                      <Todo
                        key={item?.id}
                        id={item?.id}
                        isPintle={true}
                        isChecked={item?.checked}
                        content={item?.title}
                        memo={item?.memo}
                       deleteTodoById={deleteTodoById}
                      />
                    )
                )}
              </div>
            </div>
            <div className={styles.todos}>
              {data?.map(
                (item) =>
                  !item?.pintle && (
                    <Todo
                      key={item?.id}
                      id={item?.id}
                      isChecked={item?.checked}
                      isPintle={item?.pintle}
                      content={item?.title}
                      memo={item?.memo}
                      deleteTodoById={deleteTodoById}
                    />
                  )
              )}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
