import Head from "next/head";
import Todo from "../components/Todo";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { AiOutlineAlignLeft } from "react-icons/ai";
import useTodoLogic from "../hooks/useTodoLogic";

export default function Home() {
  const { handleChange, handleKeyDown, data, getData } = useTodoLogic();

  useEffect(() => {
    getData();
  }, [data]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Todos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.todoapp}>
        <div className={styles.todo}>
          <div className={styles.header}>
            <span className={styles.title}>To Do List</span>
          </div>
          <div className={styles.form}>
            <div className={styles.addTodo}>
              <div className={styles.addTask}>
                <p>
                  <AiOutlineAlignLeft />
                </p>

                <input
                  placeholder="Add a task..."
                  name="title"
                  onChange={handleChange}
                  onKeyDown={handleKeyDown}
                  className={styles.todoInput}
                />
              </div>
              <div className={styles.pintle}>
                {data?.map(
                  (item) =>
                    item?.pinned && (
                      <Todo
                        key={item?.id}
                        id={item?.id}
                        isPinned={true}
                        isChecked={item?.checked}
                        content={item?.title}
                        memo={item?.memo}
                      />
                    )
                )}
              </div>
              <div className={styles.todos}>
                {data?.map(
                  (item) =>
                    !item?.pinned && (
                      <Todo
                        key={item?.id}
                        id={item?.id}
                        isPinned={item?.pinned}
                        isChecked={item?.checked}
                        content={item?.title}
                        memo={item?.memo}
                      />
                    )
                )}
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
